# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: debc7b932eb8c59a22513d0d22f94b6274a86a81b0906aefb8e5b62a42a84a3097193d37a1e50c393affeb5891d85de2759133049b41a262b44f94f18b655c92

test:
  secret_key_base: 7934ec3ee4eabb0f9c84e5b841d7f3c7d8c455c679f572be5b8c0fad7e5a263578bd3004bfbb3a15e0a10b0fb6bb1585181faa6b64a2b3868667429bde1114a9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
